version: '3.7'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:latest
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.publish_host=127.0.0.1
      - opendistro_security.disabled=true
      - http.cors.allow-origin=*
      - http.cors.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600

volumes:
  elasticsearch-data: