version: '3.7'
services:
  app:
    build: .
    container_name: toprec
    environment:
      - REACT_APP_ES_INDEX=tmdb
      - REACT_APP_ES_HOST=http://localhost:9200/
    ports:
      - "5335:80"
    depends_on:
      - odfe-node1
