version: '3.7'
services:
  app:
    build:
      context: .
      args:
        - REACT_APP_ES_INDEX=tmdb
        - REACT_APP_ES_HOST=http://localhost:9200/
    container_name: toprec
    ports:
      - "5335:80"
    depends_on:
      - odfe-node1
